apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-checks
  namespace: default
spec:
  schedule: "0 23 * * *"
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      parallelism: 1 
      completions: 1 
      template:
        spec:
          containers:
          - name: nightly-checks
            image: homelab.local:5000/nightly_checks:latest
            imagePullPolicy: Always
            env:
              - name: TWITCH_ACCESS_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: twitch-chat-logger
                    key: twitchAccessToken
              - name: TWITCH_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: twitch-chat-logger
                    key: twitchClientId
              - name: CONFIG_PATH
                value: "/config/deploy_config.yml"
              - name: DATABASE_HOST_ADDRESS
                value: "mysql"
          restartPolicy: Never
