apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivum-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archivum-backend
  template:
    metadata:
      labels:
        app: archivum-backend
    spec:
      containers:
        - name: archivum-backend
          image: homelab.local:5000/archivum-backend:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_PATH
              value: "/app/config_files/deploy_config.yml"
            - name: DATABASE_HOST_ADDRESS
              value: "mysql"
          ports:
          - containerPort: 8080
