apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: archivum-backend
  namespace: default
spec:
  entryPoints:
    - web
    - websecure 
  routes:
    - kind: Rule
      match: Host(`api.looank.com`)
      services:
        - kind: Service
          name: archivum-backend
          port: 8080
  tls:
    certResolver: dns-simple
